name: qualityapproach
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  http: ^1.3.0
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  pluto_grid: ^8.0.0
  equatable: ^2.0.7
  excel: ^4.0.6
  pdf: ^3.11.2
  file_picker: ^8.3.2
  universal_html: ^2.2.4
  open_file: ^3.5.10
  syncfusion_flutter_xlsio: ^28.2.4
  signature: ^5.5.0
  google_fonts: ^6.2.1
  logging: ^1.3.0
  firebase_core: ^3.13.0
  firebase_core_web: ^2.22.0
  firebase_auth_web: ^5.14.2
  firebase_auth: ^5.5.2
  file_saver: ^0.2.14
  http_parser: ^4.1.2
  printing: ^5.14.2
  freezed_annotation: ^3.0.0
  syncfusion_flutter_pdf: ^28.2.12
  image: ^4.3.0
  encrypt: ^5.0.3
  crypto: ^3.0.6
  url_launcher: ^6.3.1
  fl_chart: ^1.0.0
  flutter_spinkit: ^5.2.1
  flutter_sticky_header: ^0.7.0
  syncfusion_flutter_charts: ^28.2.12
  archive: ^3.6.1
  permission_handler: ^12.0.1
  animated_background: ^2.0.0
  camera: ^0.11.2
  confetti: ^0.8.0
  animations: ^2.0.11
  face_livelyness_detection: ^1.0.3
  flutter_map: ^8.2.1
  location: ^8.0.1
  sliding_up_panel: ^2.0.0+1
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  build_runner: ^2.4.15
  uuid: ^4.4.2

dependency_overrides:
  rxdart: ^0.28.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/Roboto-Regular.ttf
